stages:          # Список этапов и порядок их выполнения
  - build        # Сборка образов бэкенда и фронтенда
  - deploy       # Автоматический деплой на сервер преподавателя

variables:
  # Настройки прокси из шаблона преподавателя
  http_proxy: ""
  https_proxy: ""
  no_proxy: ""

# ==========================================
# 1. ЭТАП СБОРКИ (BUILD JOBS)
# ==========================================

# Сборка бэкенда Django
build-backend-job:
  stage: build
  image: docker
  environment: production
  services:
    - docker:dind
  before_script:
    # Безопасный логин в реестр GitLab через конвейер (как в шаблоне)
    - echo -n $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - echo "Сборка Docker-образа бэкенда..."
    - >
      docker build
      --pull
      --build-arg http_proxy=$http_proxy
      --build-arg https_proxy=$https_proxy
      --build-arg no_proxy=$no_proxy
      --file ./cinema/DockerFile
      --label "org.opencontainers.image.title=$CI_PROJECT_TITLE-backend"
      --label "org.opencontainers.image.url=$CI_PROJECT_URL"
      --label "org.opencontainers.image.created=$CI_JOB_STARTED_AT"
      --label "org.opencontainers.image.revision=$CI_COMMIT_SHA"
      --label "org.opencontainers.image.version=$CI_COMMIT_REF_NAME"
      --tag $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_SHA
      ./cinema
    - docker push $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_SHA

# Сборка фронтенда React
build-frontend-job:
  stage: build
  image: docker
  environment: production
  services:
    - docker:dind
  before_script:
    - echo -n $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - echo "Сборка Docker-образа фронтенда..."
    - >
      docker build
      --pull
      --build-arg http_proxy=$http_proxy
      --build-arg https_proxy=$https_proxy
      --build-arg no_proxy=$no_proxy
      --file ./cinema_site/Dockerfile
      --label "org.opencontainers.image.title=$CI_PROJECT_TITLE-frontend"
      --label "org.opencontainers.image.url=$CI_PROJECT_URL"
      --label "org.opencontainers.image.created=$CI_JOB_STARTED_AT"
      --label "org.opencontainers.image.revision=$CI_COMMIT_SHA"
      --label "org.opencontainers.image.version=$CI_COMMIT_REF_NAME"
      --tag $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_SHA
      ./cinema_site
    - docker push $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_SHA


# ==========================================
# 2. ЭТАП ДЕПЛОЯ (DEPLOY JOB)
# ==========================================
deploy-job:
  stage: deploy
  image: alpine:latest # Используем легкий образ Alpine, чтобы был доступен менеджер пакетов apk
  before_script:
    # Инициализация SSH-ключа из шаблона преподавателя
    - 'command -v ssh-agent >/dev/null || ( apk add --update openssh-client )' 
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $VM_IPADDRESS >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - echo "Деплой Fullstack приложения на сервер..."
    - >
      ssh -t $SSH_USER@$VM_IPADDRESS << EOF
        # 1. Логинимся в GitLab Registry на удаленном сервере
        echo -n $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
        
        # 2. Останавливаем и удаляем старые запущенные контейнеры (если они были)
        docker stop cinema-frontend cinema-backend || true
        docker rm cinema-frontend cinema-backend || true
        
        # 3. Запускаем обновленный бэкенд на порту 8000
        docker run --name cinema-backend \
          -p 8000:8000 \
          -e DEBUG=False \
          -d $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_SHA
          
        # 4. Запускаем обновленный фронтенд на порту 5173 (или 80, если в Dockerfile фронта стоит Nginx)
        docker run --name cinema-frontend \
          -p 5173:5173 \
          -d $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_SHA
          
        echo "Все контейнеры успешно перезапущены!"
      EOF
    - echo "Приложение успешно развернуто."
  when: manual 
    