# Generated by Django 6.0.6 on 2026-06-05 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekend_markup', models.DecimalField(decimal_places=2, default=100.0, max_digits=6, verbose_name='Наценка на выходные')),
            ],
            options={
                'verbose_name': 'Настройки цен',
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название зала')),
            ],
            options={
                'verbose_name': 'Кинозал',
                'verbose_name_plural': 'Кинозалы',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название фильма')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='Длительность (мин.)')),
                ('base_price', models.DecimalField(decimal_places=2, default=300.0, max_digits=8, verbose_name='Базовая цена фильма')),
                ('is_active', models.BooleanField(default=True, verbose_name='В прокате')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='Постер фильма')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.CreateModel(
            name='SeatTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название категории')),
                ('default_markup', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Наценка за категорию')),
            ],
            options={
                'verbose_name': 'Категория места',
            },
        ),
        migrations.CreateModel(
            name='HallSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField(verbose_name='Ряд')),
                ('seat_number', models.PositiveIntegerField(verbose_name='Место в ряду')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='app.hall', verbose_name='Зал')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.seattier', verbose_name='Категория места')),
            ],
            options={
                'verbose_name': 'Место в зале',
                'verbose_name_plural': 'Места в зале',
                'unique_together': {('hall', 'row', 'seat_number')},
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='app.hall', verbose_name='Зал')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='app.movie', verbose_name='Фильм')),
            ],
            options={
                'verbose_name': 'Сеанс',
                'verbose_name_plural': 'Сеансы',
            },
        ),
        migrations.CreateModel(
            name='SessionPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Финальная цена')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='app.session', verbose_name='Сеанс')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.seattier', verbose_name='Категория места')),
            ],
            options={
                'verbose_name': 'Цена сеанса',
                'verbose_name_plural': 'Цены сеансов',
                'unique_together': {('session', 'tier')},
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(default='guest@example.com', max_length=254, verbose_name='Email покупателя')),
                ('customer_phone', models.CharField(default='+70000000000', max_length=20, verbose_name='Телефон покупателя')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена продажи')),
                ('status', models.CharField(choices=[('booked', 'Забронирован'), ('paid', 'Оплачен'), ('canceled', 'Отменен')], default='booked', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата бронирования')),
                ('hall_seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hallseat', verbose_name='Место')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='app.session', verbose_name='Сеанс')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
                'unique_together': {('session', 'hall_seat')},
            },
        ),
    ]
