# Generated by Django 6.0.6 on 2026-06-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
