# Generated by Django 6.0.6 on 2026-06-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ticket_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='age_rating',
            field=models.CharField(choices=[('0+', '0+ (Для всех)'), ('6+', '6+ (Для детей старше 6 лет)'), ('12+', '12+ (Для детей старше 12 лет)'), ('16+', '16+ (Для лиц старше 16 лет)'), ('18+', '18+ (Запрещено для детей)')], default='16+', max_length=5, verbose_name='Возрастной рейтинг'),
        ),
    ]
